### PR TITLE
Add extended tone demo to examples

### PR DESCRIPTION
**Pull request by apendley**
Changes:
-
* Added another example for playing tones using the MacroPad library.

Notes:
-
* Please let me know if there's anything I need to change (e.g. the header, description, etc.), and I'll be happy to make the change!

### CODE REVIEW

**Review by kattni — APPROVED** [review]
Thanks for your contribution!

**Comment by kattni** [comment]
Hello, @apendley. As you can see the checks have failed. Please check out [this guide](https://learn.adafruit.com/improve-your-code-with-pylint/black) and run Black on your code, and push the update to this PR. Thanks!

**Comment by apendley** [comment]
Understood! I'll take care of it as soon as possible. Thanks!

**Comment by kattni** [comment]
@apendley It appears Pylint also failed with a trailing whitespace issue. This refers to whitespace at the end of a line or spaces on blank lines. I thought Black usually resolved that, so I'm a little confused. Are you up for troubleshooting it and trying to find the issue? If you feel like it's outside your wheelhouse, I can pull the PR down and then push the fix, but I wanted to give you the opportunity. 

If you'd like to give it a try, you can install pre-commit, which is what we use to deal with all of this, and if you run it locally within the repository, you'll have the same processes happening on your computer that run remotely here. You can find instructions [here](https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code) on setting up Pre-commit. 

Please feel free to ask any questions you might have about the process. I will be around again on Monday.

**Comment by apendley** [comment]
I don't mind giving it a shot! I would like to contribute more in the future, so it would be good for me to understand the process. I will try to fix this over the weekend if I get some time. Thanks!

**Comment by kattni** [comment]
Sounds great! Getting pre-commit setup will definitely help you in the future - we use it on all the libraries. The important thing to remember is that you install it globally once, but then you have to "install" it in each individual local repository by running `pre-commit install` from the top level of the repo directory. So it's a little bit of an extra step to remember to run that in each repo that you clone, but that's the way it's done. I'm happy to help with anything you need next week!

**Comment by apendley** [comment]
I installed `pre-commit` and fixed the issues it raised. Hopefully it will pass this time! 🤞

**Review by kattni — APPROVED** [review]
Thanks for sticking with this! Great job!

**Pull request merged**
